### ISSUE TITLE
Add documentation to setup init-tenant locally 

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-tenant#105]

**Comment by jstrachan** [comment]
fwiw its part of the fabric8 installation if thats any help. Running everything locally is probably the easiest way to develop & test it
https://github.com/fabric8io/fabric8-platform/blob/master/INSTALL.md

**Comment by jstrachan** [comment]
I guess we can resolve this as folks can just install fabric8 on minishift?
