### ISSUE TITLE
Add auto token refresh by login via developers.redhat.com

### ISSUE THREAD

**Issue by aslakknutsen** [fabric8-services/fabric8-tenant#14]
OSO does not have a service account for the master user so there is no long lived token available. Each every now and then we need to login to developers.redhat.com outside of webflow to get a fresh token on oso.

@bartoszmajsak

**Comment by bartoszmajsak** [comment]
![image](https://cloud.githubusercontent.com/assets/719616/24713389/ced8ee82-1a25-11e7-9290-8e22fbc48904.png)

**Comment by kbsingh** [comment]
![There yet](https://www.kateevanhorn.com/wp-content/uploads/2017/01/Are-We-There-Yet.jpg)

**Comment by bartoszmajsak** [comment]
Didn't we "solve" it with long living token?

**Comment by aslakknutsen** [comment]
.. not gonna happen..
