### ISSUE TITLE
Init tenant should set the correct Keycloak URL

### ISSUE THREAD

**Issue by ibuziuk** [fabric8-services/fabric8-tenant#228]
In fabric8-online[1] we have introduced two new configs for che-server:

- keycloak-oso-endpoint
- keycloak-github-endpoint

These are currently hardcoded in fabric8io configuration with KC production URLs. That's an issue because we may need to use a distinct instance of KC based on which cluster Che will be deployed to (prod / prod-preview). These 2 config maps should be configured by the tenant init script as it's already done for hostname-http

[1] https://github.com/fabric8io/fabric8-online/blob/master/apps/che/src/main/fabric8/cm.yml#L20-L21

**Comment by aslakknutsen** [comment]
Update the templates here https://github.com/fabric8io/fabric8-online/blob/master/packages/fabric8-online-che/src/main/fabric8/template.yml to add the new values and add the parameter ref to the CM. 

I'll make sure the tenant service provide the correct values

**Comment by ibuziuk** [comment]
@aslakknutsen PR to fabric8-online has been sent - https://github.com/fabric8io/fabric8-online/pull/344
