### ISSUE TITLE
add a REST API to test the users openshift + github tokens

### ISSUE THREAD

**Issue by jstrachan** [fabric8-services/fabric8-tenant#243]
it'd be good to have a REST API that tried to use the openshift + github tokens to check they are still valid.

e.g. its quite easy to recreate an openshift cluster (via say minishift) at the same URL and open the console and it thinks we're logged in as we have a cached token

A simple REST API that say, lists projects on openshift (or namespaces on kubernetes) or queries the user details on github could then report accurately if the toke is valid so that the UI could check this and if there's a failure redirect to the login page

**Comment by alexeykazakov** [comment]
I think we should have this API in https://github.com/fabric8-services/fabric8-auth instead of https://github.com/fabric8-services/fabric8-tenant.
Any objections if I move this issue to fabric8-auth?

**Comment by aslakknutsen** [comment]
@alexeykazakov I agree it's definitely not a tenant service api, but I'm not convinced it's needed at all.

**Comment by jstrachan** [comment]
to reproduce the issue:

* use fabric8 on minishift.
* trash the VM, recreate fabric8
* the browser has a token cached and its not usable for OpenShift and there's no way for the browser to know if its valid or not

So this issue was about having some REST API we can use the current OSO + github tokens to do a simple query (e.g. query Projects on OpenShift or get the users github ID on github) - if those requests fail with, say, 401 then we know the tokens are no longer valid and can be disgarded.

So its more of a helper method for the Tenant that the UI can use to know if a cached set of tokens are valid or not really. Not sure it belongs in fabric8-auth as it relates more to Tenant knowledge (e.g. using the OpenShift REST API) than being pure auth?

**Comment by aslakknutsen** [comment]
Replaced by https://github.com/fabric8-services/fabric8-auth/issues/38
