### ISSUE TITLE
Jenkins pipline CD step sends PR to promote-to-prod before centosci job is done

### ISSUE THREAD

**Issue by aslakknutsen** [fabric8-services/fabric8-tenant#247]
This cause prod to attempt to deploy new DC and OSD failing to pull image for ~5 min, assuming the centosci job finish at all

**Comment by rawlingsj** [comment]
Do you have a URL to the ci centos job?  I wonder if we can find the right job add a `waitForJobToFinish(url)` to the shared pipeline library.

**Comment by vpavlin** [comment]
@rawlingsj If I understand correctly what is happening here, this should be the job: https://ci.centos.org/view/Devtools/job/devtools-fabric8-tenant-build-master/

**Comment by rawlingsj** [comment]
OK great - is there any way to identify which build corresponds to the change so we don't watch the wrong build if we have two triggered in similar timeframes?

**Comment by vpavlin** [comment]
I think we could match either `lastBuild`

https://ci.centos.org/view/Devtools/job/devtools-fabric8-tenant-build-master/lastBuild/api/json?pretty

Or find the PR commit in all builds

https://ci.centos.org/view/Devtools/job/devtools-fabric8-tenant-build-master/api/json?tree=builds[id,changeSet[items[commitId]]]&pretty

**Comment by rawlingsj** [comment]
Fixed via https://github.com/fabric8-services/fabric8-tenant/pull/401
