### ISSUE TITLE
pq: relation "tenants" does not exist

### ISSUE THREAD

**Issue by hectorj2f** [fabric8-services/fabric8-tenant#258]
I constantly find this error in prod-preview. Is that expected ? I found these errors using this query: `"*does not exist*"`

**Comment by aslakknutsen** [comment]
No clue why f8tenant is configured to use the auth db in prod-preview? @vpavlin ?

**Comment by aslakknutsen** [comment]
@vpavlin ping

**Comment by aslakknutsen** [comment]
Prod-preview fixed
