### ISSUE TITLE
support tenant profiles (free, paid, huge, ...)

### ISSUE THREAD

**Issue by jstrachan** [fabric8-services/fabric8-tenant#355]
for running OSIO on OSIO we're gonna need a slightly different set of YAMLs for the tenant services (e.g. including a Nexus, Hubot etc). So different users may be configured/associated with a different level of tenant services.

Maybe for now we just have a free tier + prod tier flag/setting somewhere so we can have the default free YAML and a paid YAML that comes with a bit more quota/resources. Over time we could swizzle things to have more flexible mappings of users <-> templates to use for tenant services - but for now the free tier/prod tier flag might be enough

**Comment by jstrachan** [comment]
the code which applies the YAML is here: https://github.com/fabric8-services/fabric8-tenant/blob/master/openshift/init_tenant.go#L231

**Comment by jstrachan** [comment]
we maybe need some kinda attribute/flag/setting enabled via the KeyCloak admin UI and use the presence of that header to know if we should use the `paid tier` YAML?

**Comment by jstrachan** [comment]
I wonder if we should store the 'what kind of tenant is this user' data inside the fabric8-tenant database rather than tie it into KeyCloak?

**Comment by chmouel** [comment]
@aslakknutsen any idea about the best place to store those informations? Would it be better to store this in auth-db or inside f8-tenant Database?

**Comment by chmouel** [comment]
@jstrachan where do you think would be the best way to store the information of what type of tenant have which apps ? Do we have just different templates like : 

```
fabric8-tenant-user-project-large-{openshift,k8}.yaml
fabric8-tenant-user-project-medium-{openshift,k8}.yaml
fabric8-tenant-user-project-small-{openshift,k8}.yaml
```
with different LimitRanges and quota for each of those applied to it ?
