### ISSUE TITLE
provide a REST API to return all tenant namespaces created by fabric8-tenant

### ISSUE THREAD

**Issue by jstrachan** [fabric8-services/fabric8-tenant#369]
so that we can implement a `gofabric8 uninstall` command to remove all resources installed into a kubernetes/openshift cluster by fabric8

**Comment by jstrachan** [comment]
am hoping we can use an openshift token for the auth on the REST API - as we'll be invoking this from gofabric8 where we know the OS token but don't know the KC token

**Comment by chmouel** [comment]
it seems that we already have the listing tenant api with /api/tenant rest call andhttps://github.com/fabric8-services/fabric8-tenant/blob/e749e4b7dc06b755341949889939ee9d6278814c/controller/tenant.go#L233 function

Is there anything else needed?

![image](https://user-images.githubusercontent.com/98980/30584297-9b58caaa-9d29-11e7-98cb-8eb1ae4c366e.png)

**Comment by jstrachan** [comment]
yeah, we need a way to list all tenants installed on the cluster and their associated namespaces so we can uninstall them.

e.g. test cases could login with 3 different user accounts; causing 3 tenants to be created. We need a way to remove all 3 sets of tenant services for CI / CD tests or for users to clean down fabric8 installations

**Comment by fche** [comment]
BTW for OSO/tenant monitoring purposes we need such an API too.  It should be suitable for use by an OSD-side serviceaccount rather than an OSIO user.
