### ISSUE TITLE
Allow different levels of logging

### ISSUE THREAD

**Issue by chmouel** [fabric8-services/fabric8-tenant#406]
Currently it's a bit difficult to debug/develop with f8-tenant as the output logs get filled really quickly with info messages like this : 

![image](https://user-images.githubusercontent.com/98980/31491380-5e58de9e-af47-11e7-918a-6201c3c50f34.png)

It would be nice to have some sort of filtering for some of the debug messages,

**Comment by aslakknutsen** [comment]
grep -v StatusController ?
