### ISSUE TITLE
Need to update init script for setting correct values for a new GitHub token endpoint in che-sever

### ISSUE THREAD

**Issue by ibuziuk** [fabric8-services/fabric8-tenant#414]
Need to update init script for setting correct values for new GitHub token endpoint:

>  https://auth.openshift.io/api/token?for=https://github.com
>  https://auth.prod-preview.openshift.io/api/token?for=https://github.com

Related PRs
- https://github.com/fabric8-services/fabric8-tenant-che/pull/46
- https://github.com/redhat-developer/rh-che/pull/381
- https://github.com/eclipse/che/pull/6809

**Comment by ibuziuk** [comment]
@aslakknutsen will you be able to give me a hand with this (or point where this should be done) ?

**Comment by aslakknutsen** [comment]
@ibuziuk https://github.com/fabric8-services/fabric8-tenant/blob/9ae5b5870e4a782b954144c635bac037f3185617/main.go#L130
