### ISSUE TITLE
Add JENKINS_ROOT_URL environment variable

### ISSUE THREAD

**Issue by chmouel** [fabric8-services/fabric8-tenant#528]
Following this issue https://github.com/fabric8-services/fabric8-tenant-jenkins/pull/65, let get the JENKINS_ROOT_URL variable setting from the template variable and assign them.

**Comment by chmouel** [comment]
https://github.com/fabric8-services/fabric8-tenant/pull/529

**Comment by aslakknutsen** [comment]
Related to fabric8-services/fabric8-jenkins-proxy#114
