### ISSUE TITLE
What's the point of base64 encoded passwords?

### ISSUE THREAD

**Issue by kwk** [fabric8-services/fabric8-tenant#570]
What's the point of base64 encoded passwords [here](https://github.com/fabric8-services/fabric8-tenant/blob/563cd7edb89ee25ec3a9778249fa761d9a4118b6/f8tenant.secrets.yaml#L17):

```yaml
postgres.password: bXlzZWNyZXRwYXNzc3dvcmQK
```

Security through obscurity?

**Comment by aslakknutsen** [comment]
It's how Kubernetes Secrets work: https://kubernetes.io/docs/concepts/configuration/secret/
