### ISSUE TITLE
Need to perform cluster-wide tenant in order to apply `2.0.90` version of fabric8-tenant-che

### ISSUE THREAD

**Issue by ibuziuk** [fabric8-services/fabric8-tenant#651]
the latest `2.0.90` version of `fabric8-tenant-che` contains important updates required for workspace.next
- adding new `che-workspace` sa with view & exec permissions in *-che namespace [1]
- increasing quota of services to 15 [2]

Need to perform  cluster-wide tenant update in order to rollout this change to all the prod / prod-preview tenants.

[1] https://github.com/fabric8-services/fabric8-tenant-che/pull/111
[2] https://github.com/fabric8-services/fabric8-tenant-che/pull/113

**Comment by ibuziuk** [comment]
cc: @aslakknutsen @alexeykazakov @garagatyi

**Comment by garagatyi** [comment]
@aslakknutsen can we proceed with the update? It seems that no one except you can do that.

**Comment by aslakknutsen** [comment]
on it

**Comment by aslakknutsen** [comment]
blocked here atm https://github.com/fabric8-services/fabric8-tenant/pull/656

**Comment by aslakknutsen** [comment]
Preview done, prod in progress

**Comment by aslakknutsen** [comment]
Prod update done

**Comment by garagatyi** [comment]
Cool! Thanks!
