### ISSUE TITLE
allow a list of user names to be upgraded to a specific version of the tenant YAML

### ISSUE THREAD

**Issue by jstrachan** [fabric8-services/fabric8-tenant#68]
as a simpler alternative to #15 it might be simplest to just have a REST API we can use to update a list of user accounts to a given version of the fabric8-online YAML. We could then use this mechanism in pipelines to roll out a new version to a small set of test user accounts and run tests on it; then if those pass, role it out to a larger set of beta-testers before we submit the actual PR to update the init-tenant itself for all users.

I guess POSTing the YAML to use for the fabric8-online stuff might be the most flexible; as then we could test at the PR level before we merge. 

It might simplify testing if we split up the jenkins/content-repository YAML from the Che YAML so that both of those PRs could test their own changes before releasing and raising a PR?

**Comment by aslakknutsen** [comment]
> It might simplify testing if we split up the jenkins/content-repository YAML from the Che YAML so that both of those PRs could test their own changes before releasing and raising a PR?

Yea, the 'full release cycle' implied by the current setup is unnatural in the dsaas.

**Comment by jstrachan** [comment]
I've a PR coming soon to `gofabric8 tenant` that lets you specify a team version or a folder of a local build of team YAMLs for CI / CD pipelines

**Comment by jstrachan** [comment]
PR ready to go, just need this PR merged so we can link to fabric8-init-tenant code without clashing with goa/kubernetes/jwt stuff 
https://github.com/fabric8io/fabric8-init-tenant/pull/88

**Comment by bmicklea** [comment]
@aslakknutsen are you working on this?  I see it's assigned to you but it's been awhile since there was an update.
