### ISSUE TITLE
reset environment / update tenant is failing for some users [prod-preview]

### ISSUE THREAD

**Issue by ibuziuk** [fabric8-services/fabric8-tenant#697]
update tenant / reset environment is failing for `a04ab657-b7ca-408a-9243-da60057e719d` / `ibuziuk@redhat.com` user on prod-preview provisioned against https://console.free-stg.openshift.com/ 

There are no errors on UI when update tenant / reset environment button is pressed - `Success! Your OpenShift.io environment has been erased!`

![image](https://user-images.githubusercontent.com/1461122/49533259-d40e9400-f8be-11e8-8f64-1e4a0bc35605.png)

However, the actual update tenant / reset env does not happen. Quick check of the logs shows that there are some errors during update tenant / reset env:

`{"cluster_url":"https://api.free-stg.openshift.com/","err":"exit  status 1","file":"/tmp/go/src/github.com/fabric8-services/fabric8-tenant/sentry/sentry.go","func":"github.com/fabric8-services/fabric8-tenant/sentry.LogError","identity_id":"a04ab657-b7ca-408a-9243-da60057e719d","level":"error","line":48,"msg":"clean failed","namespace":"ibuziuk-che","output":"error: You must be logged in to the server (Unauthorized)\n","pid":1,"pkg":"github.com/fabric8-services/fabric8-tenant/sentry","req_headers":{"Accept-Encoding":["gzip"],"Authorization":"*****","User-Agent":["Go-http-client/1.1"],"X-Request-Id":["7CvcI9CQor-11746"]},"req_id":"7CvcI9CQor-11746","req_params":{"remove":["false"]},"time":"2018-12-05 17:31:01"} `

query for kibana `kubernetes.labels.app:"f8tenant" AND kubernetes.namespace_name:"dsaas-preview" AND  identity_id:"a04ab657-b7ca-408a-9243-da60057e719d"`

**Comment by ibuziuk** [comment]
cc: @alexeykazakov @MatousJobanek

**Comment by MatousJobanek** [comment]
@ibuziuk I'm afraid that the token provided by auth is invalid or expired. At least this is what I got when I retrieved the token from auth and used it for login to `https://api.free-stg.openshift.com/` locally: 
`error: The token provided is invalid or expired.`
any thoughts @xcoulon @dipak-pawar @sbose78

**Comment by alexeykazakov** [comment]
What taken are you talking about?
OpenShift user token? Try to relink your account in user setting page. It will refresh the token.

**Comment by MatousJobanek** [comment]
@ibuziuk I'm afraid that the token provided by auth is invalid or expired. At least this is what I got when I retrieved the token from auth and used it for login to `https://api.free-stg.openshift.com/` locally: 
`error: The token provided is invalid or expired.`
any thoughts @xcoulon @dipak-pawar @sbose78

**Comment by MatousJobanek** [comment]
Sorry, not OpenShift user, but cluster token for `devtools-sre` user

**Comment by MatousJobanek** [comment]
What I tried:
1. POST https://auth.prod-preview.openshift.io/api/token with tenant service account info -> received bearer token
2. GET https://auth.prod-preview.openshift.io/api/token?for=https%3A%2F%2Fapi.free-stg.openshift.com%2F\u0026force_pull=false using the bearer token -> receied token for devtools-sre user for the cluster
3. oc login https://api.free-stg.openshift.com/ --token=devtools_sre_token -> got `error: The token provided is invalid or expired.`

**Comment by alexeykazakov** [comment]
OK. The token got invalidated. We need to update our configuration.

**Comment by nurali-techie** [comment]
@MatousJobanek the token you get in 

> What I tried:
> 
> 1. POST https://auth.prod-preview.openshift.io/api/token with tenant service account info -> received bearer token
> 2. GET [https://auth.prod-preview.openshift.io/api/token?for=https%3A%2F%2Fapi.free-stg.openshift.com%2F\u0026force_pull=false](https://auth.prod-preview.openshift.io/api/token?for=https%3A%2F%2Fapi.free-stg.openshift.com%2F%5Cu0026force_pull=false) using the bearer token -> receied token for devtools-sre user for the cluster
> 3. oc login https://api.free-stg.openshift.com/ --token=devtools_sre_token -> got `error: The token provided is invalid or expired.`

@MatousJobanek the token you get in step2 is encrypted and you should have decrypted it before using in step3 .. right ??

**Comment by MatousJobanek** [comment]
> @MatousJobanek the token you get in step2 is encrypted and you should have decrypted it before using in step3 .. right ??

of course that I did, I just didn't see it important to mention it here as it seemed obvious to me :-) - I did the same approach also for `https://api.starter-us-east-2a.openshift.com` (just to check that I was doing the correct steps) and I was able to successfully login.

**Comment by ppitonak** [comment]
Environment reset seems to work now, can you verify @ibuziuk ?

**Comment by ibuziuk** [comment]
@ppitonak seems to work for me \o/
but IMO there is still a problem that UI does not show any errors when smth. wrong happens during tenant-update / reset env. (AFAIK it will always show `Success! Your OpenShift.io environment has been erased!` even if there would be errors on `init-tenant` side ) cc: @joshuawilson

**Comment by ppitonak** [comment]
Should we create a new issue for that?

**Comment by ibuziuk** [comment]
@ppitonak yeah, probably. Do you want me to create one ?

**Comment by ppitonak** [comment]
yes, please do

**Comment by ibuziuk** [comment]
Created a separate issue for UI update https://github.com/openshiftio/openshift.io/issues/4630
Closing

**Comment by ibuziuk** [comment]
@MatousJobanek not sure I should have closed. Feel free to reopen if smth. else needs to be updated
